### PR TITLE
feat : added the bitcoin-connect docs onto a new branch deploy-folder

### LINKED ISSUE #159: Dedicated documentation site
The README is very long and not very readable / developer friendly

Is there something open source so people can still contribute?

### PR DESCRIPTION
**Pull request by vr-varad**
## Description
This pull requests all the docusaurus docs website to the deploy-folder branch.
## Resolves 
#159

### CODE REVIEW

**Comment by vr-varad** [comment]
I apologize for my negligence last time ;)

**Comment by vr-varad** [comment]
With Docusaurus I need a repo with the docusaurus website like I did  inside https://github.com/vr-varad/bitcoin-connect-docs
and I deployed on GitHub pages https://vr-varad.github.io/bitcoin-connect-docs/
Certainly! If you could please provide more details or clarify your question, I would be happy to help.

**Comment by vr-varad** [comment]
Hey @rolznz  can u guide me a little bit? more so that I can work on it without any issues and problems.

**Comment by rolznz** [comment]
Hi, the newly-deployed site looks better now - the left sidebar items are mostly good now.

https://vr-varad.github.io/bitcoin-connect-docs/usage/other_frameworks however contains Pure HTML - can you move that out into its own section? 

And https://vr-varad.github.io/bitcoin-connect-docs/faq is broken - "Need help?" and FAQ should be split and each FAQ item should be a separate subpage.

Could you look at https://medium.com/@nathvichea/github-action-to-deploy-docusaurus-8c297eaf1514 ? Ideally we can use a github action to build the site so it'll be updated on every commit.

I was originally hoping to also see these additions in a fork of Bitcoin Connect, not a completely separate documentation repository.

**Comment by vr-varad** [comment]
Sure I am working on it;)

**Comment by vr-varad** [comment]
I applied the GitHub Actions. Should I update the PR??? @rolznz

**Comment by vr-varad** [comment]
I am trying to put a custom domain to it as bitcoin-connect-docs.com but it shows me 
``` Both bitcoin-connect-docs.com and its alternate name are improperly configured```
What could I do any ideas? @rolznz

**Comment by rolznz** [comment]
@vr-varad did you buy that domain? I wouldn't expect you to do that. For example, we could use a subdomain on our existing domain like docs.bitcoinconnect.com

**Comment by vr-varad** [comment]
so should i commit the changes I made into this PR @rolznz  and also change the docs link in the main website

**Comment by vr-varad** [comment]
@rolznz any further updates?

**Comment by rolznz** [comment]
@vr-varad I think I have given you enough information to work on the issue.

**Comment by vr-varad** [comment]
Hey @rolznz, I sincerely apologize for bombarding you with so many questions. I hope you can forgive my eagerness. I just wanted to kindly inquire about the progress regarding the changes I made to the documentation website. If it's convenient for you, could you please inform me if I should proceed with implementing these changes on the main website? If so, could you please guide me on where to find the codebase for the main website? If not, I completely understand, and I would appreciate your guidance on what steps should be taken next. Once again, I apologize for any inconvenience caused by my inquiries. Your assistance is greatly appreciated. Thank you for your understanding.

**Comment by rolznz** [comment]
Hi @vr-varad we do not want any changes on the main website. This should be an isolated documentation site hosted on github pages.

**Comment by vr-varad** [comment]
So @rolznz can I go for another issue.

**Comment by vr-varad** [comment]
Hey @rolznz, I just wanted to extend my gratitude for your assistance. Looking forward to collaborating more in the future. By the way, Appreciate any advice or support you can offer on this. Thanks again! I've got my eye on tackling issue #21.

**Comment by vr-varad** [comment]
Any particular issue I could work on?

**Comment by rolznz** [comment]
@vr-varad do you not want to finish this one? you should be able to re-read the requirements I gave in this ticket

**Comment by rolznz** [comment]
closing due to inactivity

**Pull request closed without merging**
