### PR TITLE
Improve wallet filter

### PR DESCRIPTION
**Pull request by rleed**
Hey guys, we on the FanFares project need better filtering and want to share what we've come up with initially. What do you think of this increment?

### CODE REVIEW

**Comment by rolznz** [comment]
Hi @rleed 

Cool your using Bitcoin Connect at https://fanfares.io/ !

Could you tell us about why you'd only want to enable certain connectors? what's the benefit of doing this?

I paid for a PlebChain radio at fanfares.io but declined to sign the request to sign a NIP-56 event. It didn't let me watch the episode.

**Comment by rleed** [comment]
> Hi @rleed
> 
> Cool your using Bitcoin Connect at https://fanfares.io/ !
> 
> Could you tell us about why you'd only want to enable certain connectors? what's the benefit of doing this?

Hey thanks for checking us out.

We need the filter until we expand our back-end to support more than just Alby payments. Our current implementation was put in place when Alby was the only service that allowed payment verification, and we have some non-trivial work to do to generalize the payment verification logic. Until then, we want to avoid allowing the user to pay in ways that will result in them not receiving the episode...

> I paid for a PlebChain radio at fanfares.io but declined to sign the request to sign a NIP-56 event. It didn't let me watch the episode.

Similar case in point... very sorry about that... I'll see what we can do

**Comment by rolznz** [comment]
Hi @rleed 

How does the verification work? are you using LNURL-verify?

All the connectors support the common WebLN interface. It should not matter which connector you pay with - it's the same `provider.sendPayment` call and they all return a preimage.

**Comment by arkin0x** [comment]
@rolznz Hey there, Arkinox with fanfares.io here.

1. I found your alby address in your github profile and refunded you for your podcast purchase. I'm terribly sorry about that!
2. The signature that you declined is required to unlock the podcast. We will improve our UI so that the user understands this. I appreciate you trying it out.
3. The reason we need to restrict to Alby is we are using this to verify the podcast purchase for unlock: https://guides.getalby.com/developer-guide/v/alby-wallet-api/reference/api-reference/invoices#get-a-specific-invoice This isn't available outside of Alby, but as @rleed said we are rewriting our backend to do away with this. The filtering was a stopgap to prevent failing purchases until we finish this.

Thank you!

**Comment by rolznz** [comment]
Hi @arkin0x - if it's just a stopgap, are you able to be OK with just running a fork for now?

But I'm curious, the Alby connector in Bitcoin Connect is actually powered by NWC. So the API endpoint you linked should not work (that uses the Alby OAuth API which is completely unrelated - and it requires an invoices:read scope, therefore an OAuth access token, so the frontend shouldn't be able to call this).

**Comment by arkin0x** [comment]
Hey @rolznz . We don't mind running a fork. We just wanted to contribute.

We have a server that ultimately makes the call to verify the invoice so it isn't running through NWC.

**Comment by rolznz** [comment]
> We have a server that ultimately makes the call to verify the invoice so it isn't running through NWC.

@arkin0x thanks. If that's the case, did the server also generate the invoice? then it shouldn't matter which Bitcoin Connect connector is used, because it's only used to pay the invoice.

> We don't mind running a fork. We just wanted to contribute.

Thanks! We just have to be careful because the more options and configuration we add will make Bitcoin Connect more complex to develop and use.

**Comment by rolznz** [comment]
Closing for now. If you have any concerns, let me know!

**Pull request closed without merging**
