### PR TITLE
Replace success gif with svg animation

### PR DESCRIPTION
**Pull request by hzrd149**
This MR replaces the existing gif animation in `src/components/images/success.ts` with a custom SVG animation.
I tried to keep the colors and timing the same, and to my unskilled eye it looks almost identical

image

## Before
`components/images/success.ts`: 222kB

Output size: 964kB
Screenshot from 2023-11-26 11-14-16

## After
`components/images/success.ts`: 1.5kB

Output size: 748kB
Screenshot from 2023-11-26 11-14-09

### CODE REVIEW

**Comment by rolznz** [comment]
Wow @hzrd149 , thanks very much for this!

Partially fixes https://github.com/getAlby/bitcoin-connect/issues/100

**Comment by rolznz** [comment]
@hzrd149 how did you create this animation, out of interest?

**Comment by rolznz** [comment]
CC @stackingsaunter

**Comment by hzrd149** [comment]
> @hzrd149 how did you create this animation, out of interest?

Sketched it up in inkscape then went back to my good old friend the `<animate/>` tag :grin: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate
The old svg animation tags kind of suck. but they have universal support and they are pretty small

**Comment by stackingsaunter** [comment]
Lovely!

**Pull request merged**
